// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// THIS FILE WAS AUTOGENERATED
import { Domain } from './Domain'
import { SeverityLevel } from './SeverityLevel'
import { DataSanitizer } from '../DataSanitizer'

interface MessageDataInterface { /**
	 * Trace message
	 */
	message: string;

	/**
	 * Trace severity level.
	 */
	severityLevel?: SeverityLevel;

	/**
	 * Collection of custom properties.
	 */
	properties?: any;

	/**
	 * Collection of custom measurements.
	 */
	measurements?: any;

}

/**
 * Instances of Message represent printf-like trace statements that are text-searched. Log4Net, NLog and other text-based log file entries are translated into intances of this type. The message does not have measurements.
 */
export class MessageData extends Domain { /**
	 * Schema version
	 */
	public ver : number

	/**
	 * Trace message
	 */
	public message: string

	/**
	 * Trace severity level.
	 */
	public severityLevel?: SeverityLevel

	/**
	 * Collection of custom properties.
	 */
	public properties?: any

	/**
	 * Collection of custom measurements.
	 */
	public measurements?: any

	constructor(options : MessageDataInterface) {
		super()

		this.ver = 2
		this.properties = DataSanitizer.sanitizeProperties(options.properties || {})
		this.measurements = DataSanitizer.sanitizeMeasurements(options.measurements || {})

		this.message = DataSanitizer.sanitizeMessage(options.message)
		this.severityLevel = options.severityLevel
	}
}
