// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// THIS FILE WAS AUTOGENERATED
import { Domain } from './Domain'
import { DataSanitizer } from '../DataSanitizer'

interface RequestDataInterface{
	/**
	 * Identifier of a request call instance. Used for correlation between request and other telemetry items.
	 */
	id: string;

	/**
	 * Source of the request. Examples are the instrumentation key of the caller or the ip address of the caller.
	 */
	source?: string;

	/**
	 * Name of the request. Represents code path taken to process request. Low cardinality value to allow better grouping of requests. For HTTP requests it represents the HTTP method and URL path template like 'GET /values/{id}'.
	 */
	name?: string;

	/**
	 * Response code of the request.
	 */
	responseCode: string;

	/**
	 * Indication of successfull or unsuccessfull call.
	 */
	success?: boolean;

	/**
	 * Duration of the request in DD.HH:MM:SS.MMMMMM format.
	 */
	duration: string;

	/**
	 * Request URL with all query string parameters.
	 */
	url?: string;

	/**
	 * Collection of custom properties.
	 */
	properties?: any;

	/**
	 * Collection of custom measurements.
	 */
	measurements?: any;
}
/**
 * An instance of Request represents completion of an external request to the application to do work and contains a summary of that request execution and the results.
 */
export class RequestData extends Domain {
	/**
	 * Schema version
	 */
	public ver: number

	/**
	 * Identifier of a request call instance. Used for correlation between request and other telemetry items.
	 */
	public id: string

	/**
	 * Source of the request. Examples are the instrumentation key of the caller or the ip address of the caller.
	 */
	public source: string

	/**
	 * Name of the request. Represents code path taken to process request. Low cardinality value to allow better grouping of requests. For HTTP requests it represents the HTTP method and URL path template like 'GET /values/{id}'.
	 */
	public name: string

	/**
	 * Response code of the request.
	 */
	public responseCode: string

	/**
	 * Indication of successfull or unsuccessfull call.
	 */
	public success: boolean

	/**
	 * Duration of the request in DD.HH:MM:SS.MMMMMM format.
	 */
	public duration: string

	/**
	 * Request URL with all query string parameters.
	 */
	public url: string

	/**
	 * Collection of custom properties.
	 */
	public properties: any

	/**
	 * Collection of custom measurements.
	 */
	public measurements: any

	constructor(options:RequestDataInterface) {
		super()

		this.ver = 2
		this.properties = DataSanitizer.sanitizeProperties(options.properties || {})
		this.measurements = DataSanitizer.sanitizeMeasurements(options.measurements || {})

		this.duration = DataSanitizer.sanitizeString(options.duration)
		this.id = DataSanitizer.sanitizeKey(options.id)
		this.name = DataSanitizer.sanitizeKey(options.name)
		this.responseCode = DataSanitizer.sanitizeString(options.responseCode)
		this.source = DataSanitizer.sanitizeString(options.source)
		this.success = options.success
		this.url = DataSanitizer.sanitizeUrl(options.url)
	}
}
